#include <stdio.h>
#include <stdint.h>
#include <stddef.h>

// Copy the C struct definition
typedef struct {
	// Core race information
	int syscall1_idx; // First syscall in the race pair
	int syscall2_idx; // Second syscall in the race pair
	int syscall1_num;
	int syscall2_num;
	// Extended metadata from executor
	uint64_t varName1;   // First variable name identifier
	uint64_t varName2;   // Second variable name identifier
	uint64_t call_stack1; // Callstack hash for first access
	uint64_t call_stack2; // Callstack hash for second access
	int sn1;
	int sn2;
	uint64_t signal;     // Race signal generated by executor (based on varname1+varname2+callstack hashes)
	// Additional context
	uint32_t lock_type;    // Lock type (e.g., mutex, rwlock)
	uint32_t access_type1; // First access type (read/write/free)
	uint32_t access_type2; // Second access type (read/write/free)
	uint64_t time_diff;    // Time difference between accesses (nanoseconds)
} may_race_pair_t;

int main() {
    printf("C may_race_pair_t struct size: %zu bytes\n", sizeof(may_race_pair_t));
    
    printf("Field offsets:\n");
    printf("  syscall1_idx: %zu\n", offsetof(may_race_pair_t, syscall1_idx));
    printf("  syscall2_idx: %zu\n", offsetof(may_race_pair_t, syscall2_idx));
    printf("  syscall1_num: %zu\n", offsetof(may_race_pair_t, syscall1_num));
    printf("  syscall2_num: %zu\n", offsetof(may_race_pair_t, syscall2_num));
    printf("  varName1: %zu\n", offsetof(may_race_pair_t, varName1));
    printf("  varName2: %zu\n", offsetof(may_race_pair_t, varName2));
    printf("  call_stack1: %zu\n", offsetof(may_race_pair_t, call_stack1));
    printf("  call_stack2: %zu\n", offsetof(may_race_pair_t, call_stack2));
    printf("  sn1: %zu\n", offsetof(may_race_pair_t, sn1));
    printf("  sn2: %zu\n", offsetof(may_race_pair_t, sn2));
    printf("  signal: %zu\n", offsetof(may_race_pair_t, signal));
    printf("  lock_type: %zu\n", offsetof(may_race_pair_t, lock_type));
    printf("  access_type1: %zu\n", offsetof(may_race_pair_t, access_type1));
    printf("  access_type2: %zu\n", offsetof(may_race_pair_t, access_type2));
    printf("  time_diff: %zu\n", offsetof(may_race_pair_t, time_diff));
    
    // Print raw memory layout analysis
    printf("\nMemory layout analysis:\n");
    may_race_pair_t test_pair = {0};
    test_pair.time_diff = 0x123456789ABCDEF0ULL;
    
    unsigned char* bytes = (unsigned char*)&test_pair;
    printf("Bytes around time_diff field (offset %zu):\n", offsetof(may_race_pair_t, time_diff));
    for (int i = 72; i < 88; i++) {
        printf("  byte[%d] = 0x%02x\n", i, bytes[i]);
    }
    
    return 0;
}
