package ddrd

// MayRacePair represents a race condition pair transmitted from executor
// This structure MUST match exactly with may_race_pair_t in executor/ddrd.h
// CRITICAL: Keep field order and sizes EXACTLY matching the C struct!
type MayRacePair struct {
	// Core race information (4 bytes each) - MUST match C int size
	Syscall1Idx int32 // First syscall index in the race pair
	Syscall2Idx int32 // Second syscall index in the race pair
	Syscall1Num int32 // First syscall number
	Syscall2Num int32 // Second syscall number

	// Extended metadata from executor (8 bytes each)
	VarName1   uint64 // First variable name identifier
	VarName2   uint64 // Second variable name identifier
	CallStack1 uint64 // Callstack hash for first access
	CallStack2 uint64 // Callstack hash for second access

	// Keep same order as C struct
	Sn1    int32  // Must match C struct field order
	Sn2    int32  // Must match C struct field order
	Signal uint64 // Race signal generated by executor

	// Additional context - single bytes like in C
	LockType    uint8 // Lock type (e.g., mutex, rwlock)
	AccessType1 uint8 // First access type (read/write/free)
	AccessType2 uint8 // Second access type (read/write/free)
	// C struct has no explicit padding here, so neither should we
	// The compiler will handle alignment automatically

	TimeDiff uint64 // Time difference between accesses (nanoseconds)
}
