package syzkcsanparser
























































































































































































































































































































}	}		fmt.Printf("  %s: %d\n", sorted[i].Key, sorted[i].Value)	for i := 0; i < len(sorted) && i < 10; i++ {	}		}			}				sorted[i], sorted[j] = sorted[j], sorted[i]			if sorted[j].Value > sorted[i].Value {		for j := i + 1; j < len(sorted); j++ {	for i := 0; i < len(sorted); i++ {	// Simple bubble sort for top 10	}		sorted = append(sorted, kv{k, v})	for k, v := range funcPairs {	var sorted []kv	}		Value int		Key   string	type kv struct {	// Sort and print top 10	fmt.Println("\nTop Function Pairs:")	}		fmt.Printf("  %s: %d\n", t, count)	for t, count := range typeCount {	fmt.Println("\nAccess Type Distribution:")	}		funcPairs[funcKey]++		funcKey := fmt.Sprintf("%s <-> %s", pair.Access1.Function, pair.Access2.Function)		typeCount[key]++		key := fmt.Sprintf("%s-%s", pair.Access1.Type, pair.Access2.Type)	for _, pair := range pairs {	funcPairs := make(map[string]int)	typeCount := make(map[string]int)	// Count by access type combination	fmt.Println("\n=== Race Pair Summary ===")func printSummary(pairs []RacePair) {}	return stack	}		}			stack = append(stack, strings.TrimSpace(match[1]))		if match != nil {		match := frameRe.FindStringSubmatch(line)		}			break		if strings.HasPrefix(line, "Reported by") {		}			break		if strings.HasPrefix(line, "read ") || strings.HasPrefix(line, "write ") {		}			continue		if strings.TrimSpace(line) == "" {		// Stop at empty line or next section	for _, line := range lines {	frameRe := regexp.MustCompile(`^\s+(\S+\+0x[0-9a-fA-F]+/0x[0-9a-fA-F]+.*)`)	// Stack frames start with a space and contain function+offset	lines := strings.Split(report[idx+len(accessLine):], "\n")	}		return stack	if idx == -1 {	idx := strings.Index(report, accessLine)	// Find the position after the access line	var stack []stringfunc parseCallStack(report, accessLine string) []string {}	return access, nil	}		}			access.SourceLoc = locMatch[1]		if locMatch != nil {		locMatch := locRe.FindStringSubmatch(access.CallStack[0])		locRe := regexp.MustCompile(`(\S+:\d+)`)		// Extract source location		}			access.Offset = funcMatch[2]			access.Function = funcMatch[1]		if funcMatch != nil {		funcMatch := funcRe.FindStringSubmatch(access.CallStack[0])		funcRe := regexp.MustCompile(`(\S+)\+0x([0-9a-fA-F]+)/0x[0-9a-fA-F]+`)		// Extract function name and offset from first stack frame	if len(access.CallStack) > 0 {	access.CallStack = parseCallStack(report, match[0])	// Parse call stack	access.CPU, _ = strconv.Atoi(match[5])	access.TaskID, _ = strconv.Atoi(match[4])	access.Size, _ = strconv.Atoi(match[3])	access.Address = match[2]	access.Type = match[1]	}		return access, fmt.Errorf("access record not found")	} else {		match = matches[1]	} else if !first && len(matches) >= 2 {		match = matches[0]	if first && len(matches) >= 1 {	var match []string	}		return access, fmt.Errorf("no access record found")	if len(matches) == 0 {	matches := accessRe.FindAllStringSubmatch(report, -1)	accessRe := regexp.MustCompile(`(read|write) to (0x[0-9a-fA-F]+) of (\d+) bytes by task (\d+) on cpu (\d+):`)	// or "read to 0x... of N bytes by task X on cpu Y:"	// Pattern for access line: "write to 0x... of N bytes by task X on cpu Y:"	var access AccessRecordfunc parseAccessRecord(report string, first bool) (AccessRecord, error) {}	return report, nil	report.RacePair.RawReport = reportText	}		report.RacePair.Access2 = access2	if err == nil {	access2, err := parseAccessRecord(reportText, false)	}		report.RacePair.Access1 = access1	if err == nil {	access1, err := parseAccessRecord(reportText, true)	// Parse access records	}		report.Function2 = headerMatch[2]		report.Function1 = headerMatch[1]	if headerMatch != nil {	headerMatch := headerRe.FindStringSubmatch(reportText)	headerRe := regexp.MustCompile(`BUG: KCSAN: data-race in (\S+) / (\S+)`)	// Parse the header: "BUG: KCSAN: data-race in func1 / func2"	reportText := content[startIdx : startIdx+endIdx]	}		endIdx = len(content) - startIdx	if endIdx == -1 {	endIdx := strings.Index(content[startIdx:], "==================================================================")	}		return report, fmt.Errorf("no KCSAN report found")	if startIdx == -1 {	startIdx := strings.Index(content, "BUG: KCSAN:")	// Find the KCSAN report section	var report KCSANReportfunc parseKCSANReport(content string) (KCSANReport, error) {}	return reports, nil	}		}			break			reports = append(reports, report)			}				continue				}					fmt.Printf("Warning: failed to parse %s: %v\n", logFile, err)				if *flagVerbose {			if err != nil {			report, err := parseKCSANReport(string(content))			}				continue			if err != nil {			content, err := os.ReadFile(logFile)		for _, logFile := range logFiles {		logFiles, _ := filepath.Glob(filepath.Join(crashDir, "log*"))		// Find and parse the log file		}			continue		if !strings.Contains(string(desc), "KCSAN") {		}			continue		if err != nil {		desc, err := os.ReadFile(descFile)		// Check if it's a KCSAN report		descFile := filepath.Join(crashDir, "description")		crashDir := filepath.Join(dir, entry.Name())		// Each crash is in a subdirectory		}			continue		if !entry.IsDir() {	for _, entry := range entries {	}		return nil, err	if err != nil {	entries, err := os.ReadDir(dir)	var reports []KCSANReportfunc parseKCSANDirectory(dir string) ([]KCSANReport, error) {}	printSummary(racePairs)	// Print summary	fmt.Printf("Race pairs written to %s\n", *flagOutput)	}		os.Exit(1)		fmt.Fprintf(os.Stderr, "Error writing output: %v\n", err)	if err := os.WriteFile(*flagOutput, output, 0644); err != nil {	}		os.Exit(1)		fmt.Fprintf(os.Stderr, "Error marshaling JSON: %v\n", err)	if err != nil {	output, err := json.MarshalIndent(racePairs, "", "  ")	// Output results	}		racePairs = append(racePairs, report.RacePair)		report.RacePair.ID = i + 1	for i, report := range reports {	var racePairs []RacePair	// Extract race pairs	fmt.Printf("Found %d KCSAN race reports\n", len(reports))	}		os.Exit(1)		fmt.Fprintf(os.Stderr, "Error parsing crash directory: %v\n", err)	if err != nil {	reports, err := parseKCSANDirectory(*flagCrashDir)	}		os.Exit(1)		fmt.Fprintf(os.Stderr, "Usage: %s -crash-dir <dir> [-output <file>] [-v]\n", os.Args[0])	if *flagCrashDir == "" {	flag.Parse()func main() {)	flagVerbose  = flag.Bool("v", false, "verbose output")	flagOutput   = flag.String("output", "race_pairs.json", "output JSON file")	flagCrashDir = flag.String("crash-dir", "", "directory containing KCSAN crash reports")var (}	RacePair  RacePair	Function2 string `json:"function2"`	Function1 string `json:"function1"`type KCSANReport struct {// KCSANReport represents a parsed KCSAN report}	RawReport string       `json:"raw_report,omitempty"`	Access2   AccessRecord `json:"access2"`	Access1   AccessRecord `json:"access1"`	ID        int          `json:"id"`type RacePair struct {// RacePair represents a detected data race between two accesses}	CallStack []string `json:"call_stack"` // full call stack	SourceLoc string   `json:"source_loc"` // source file:line	Offset    string   `json:"offset"`     // function offset	Function  string   `json:"function"`   // function name	CPU       int      `json:"cpu"`        // CPU number	TaskID    int      `json:"task_id"`    // task/thread ID	Size      int      `json:"size"`       // access size in bytes	Address   string   `json:"address"`    // memory address	Type      string   `json:"type"`       // "read" or "write"type AccessRecord struct {// AccessRecord represents a single memory access in a race)	"strings"	"strconv"	"regexp"	"path/filepath"	"os"	"fmt"	"flag"	"encoding/json"	"bufio"import (package main// in a format compatible with DDRD-syzkaller for comparison.// syz-kcsan-parser parses KCSAN data race reports and extracts race pairs// Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.// Copyright 2024 syzkaller project authors. All rights reserved.