// For some context need to synchronize on fuzzer and executor
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    LOCK_NO_LOCKS = 0,              // 双方都无锁
    LOCK_ONE_SIDED_LOCK = 1,        // 一方有锁，一方无锁
    LOCK_UNSYNC_LOCKS = 2,          // 双方有锁，但无公共锁
    LOCK_SYNC_WITH_COMMON_LOCK = 3  // 双方有锁，且有公共锁
} LockStatus;


// for transmit the race pair information from executor to fuzzer
// which i think should be same with the MayRacePair in the /pkg/ddrd/types.go 
typedef struct {
	// Core race information
	int syscall1_idx; // First syscall in the race pair
	int syscall2_idx; // Second syscall in the race pair
	int syscall1_num;
	int syscall2_num;
	// Extended metadata from executor
	uint64_t varName1;   // First variable name identifier
	uint64_t varName2;   // Second variable name identifier
	uint64_t call_stack1; // Callstack hash for first access
	uint64_t call_stack2; // Callstack hash for second access
	int sn1;
	int sn2;
	uint64_t signal;     // Race signal generated by executor (based on varname1+varname2+callstack hashes)
	// Additional context
	uint32_t lock_type;    // Lock type (e.g., mutex, rwlock)
	uint32_t access_type1; // First access type (read/write/free)
	uint32_t access_type2; // Second access type (read/write/free)
	uint64_t time_diff;    // Time difference between accesses (nanoseconds)
} may_race_pair_t;



#ifdef __cplusplus
}
#endif