// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import "strconv"

type CallFlag byte

const (
	CallFlagExecuted         CallFlag = 1
	CallFlagFinished         CallFlag = 2
	CallFlagBlocked          CallFlag = 4
	CallFlagFaultInjected    CallFlag = 8
	CallFlagCoverageOverflow CallFlag = 16
)

var EnumNamesCallFlag = map[CallFlag]string{
	CallFlagExecuted:         "Executed",
	CallFlagFinished:         "Finished",
	CallFlagBlocked:          "Blocked",
	CallFlagFaultInjected:    "FaultInjected",
	CallFlagCoverageOverflow: "CoverageOverflow",
}

var EnumValuesCallFlag = map[string]CallFlag{
	"Executed":         CallFlagExecuted,
	"Finished":         CallFlagFinished,
	"Blocked":          CallFlagBlocked,
	"FaultInjected":    CallFlagFaultInjected,
	"CoverageOverflow": CallFlagCoverageOverflow,
}

func (v CallFlag) String() string {
	if s, ok := EnumNamesCallFlag[v]; ok {
		return s
	}
	return "CallFlag(" + strconv.FormatInt(int64(v), 10) + ")"
}
