// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConnectHelloRawT struct {
	Cookie uint64 `json:"cookie"`
}

func (t *ConnectHelloRawT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	ConnectHelloRawStart(builder)
	ConnectHelloRawAddCookie(builder, t.Cookie)
	return ConnectHelloRawEnd(builder)
}

func (rcv *ConnectHelloRaw) UnPackTo(t *ConnectHelloRawT) {
	t.Cookie = rcv.Cookie()
}

func (rcv *ConnectHelloRaw) UnPack() *ConnectHelloRawT {
	if rcv == nil { return nil }
	t := &ConnectHelloRawT{}
	rcv.UnPackTo(t)
	return t
}

type ConnectHelloRaw struct {
	_tab flatbuffers.Table
}

func GetRootAsConnectHelloRaw(buf []byte, offset flatbuffers.UOffsetT) *ConnectHelloRaw {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConnectHelloRaw{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsConnectHelloRaw(buf []byte, offset flatbuffers.UOffsetT) *ConnectHelloRaw {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConnectHelloRaw{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ConnectHelloRaw) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConnectHelloRaw) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConnectHelloRaw) Cookie() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ConnectHelloRaw) MutateCookie(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func ConnectHelloRawStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ConnectHelloRawAddCookie(builder *flatbuffers.Builder, cookie uint64) {
	builder.PrependUint64Slot(0, cookie, 0)
}
func ConnectHelloRawEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
