// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import "strconv"

type Const uint64

const (
	ConstSnapshotDoorbellSize Const = 4096
	ConstMaxInputSize         Const = 4198400
	ConstMaxOutputSize        Const = 14680064
	ConstSnapshotShmemSize    Const = 33554432
)

var EnumNamesConst = map[Const]string{
	ConstSnapshotDoorbellSize: "SnapshotDoorbellSize",
	ConstMaxInputSize:         "MaxInputSize",
	ConstMaxOutputSize:        "MaxOutputSize",
	ConstSnapshotShmemSize:    "SnapshotShmemSize",
}

var EnumValuesConst = map[string]Const{
	"SnapshotDoorbellSize": ConstSnapshotDoorbellSize,
	"MaxInputSize":         ConstMaxInputSize,
	"MaxOutputSize":        ConstMaxOutputSize,
	"SnapshotShmemSize":    ConstSnapshotShmemSize,
}

func (v Const) String() string {
	if s, ok := EnumNamesConst[v]; ok {
		return s
	}
	return "Const(" + strconv.FormatInt(int64(v), 10) + ")"
}
