// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CorpusTriagedRawT struct {
}

func (t *CorpusTriagedRawT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	CorpusTriagedRawStart(builder)
	return CorpusTriagedRawEnd(builder)
}

func (rcv *CorpusTriagedRaw) UnPackTo(t *CorpusTriagedRawT) {
}

func (rcv *CorpusTriagedRaw) UnPack() *CorpusTriagedRawT {
	if rcv == nil { return nil }
	t := &CorpusTriagedRawT{}
	rcv.UnPackTo(t)
	return t
}

type CorpusTriagedRaw struct {
	_tab flatbuffers.Table
}

func GetRootAsCorpusTriagedRaw(buf []byte, offset flatbuffers.UOffsetT) *CorpusTriagedRaw {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CorpusTriagedRaw{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsCorpusTriagedRaw(buf []byte, offset flatbuffers.UOffsetT) *CorpusTriagedRaw {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CorpusTriagedRaw{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *CorpusTriagedRaw) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CorpusTriagedRaw) Table() flatbuffers.Table {
	return rcv._tab
}

func CorpusTriagedRawStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func CorpusTriagedRawEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
