// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DdrdRawT struct {
	UafPairs    []*DdrdUafPairRawT         `json:"uaf_pairs"`
	ExtendedUaf []*DdrdExtendedUafPairRawT `json:"extended_uaf"`
}

func (t *DdrdRawT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	uafPairsOffset := flatbuffers.UOffsetT(0)
	if t.UafPairs != nil {
		uafPairsLength := len(t.UafPairs)
		uafPairsOffsets := make([]flatbuffers.UOffsetT, uafPairsLength)
		for j := 0; j < uafPairsLength; j++ {
			uafPairsOffsets[j] = t.UafPairs[j].Pack(builder)
		}
		DdrdRawStartUafPairsVector(builder, uafPairsLength)
		for j := uafPairsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(uafPairsOffsets[j])
		}
		uafPairsOffset = builder.EndVector(uafPairsLength)
	}
	extendedUafOffset := flatbuffers.UOffsetT(0)
	if t.ExtendedUaf != nil {
		extendedUafLength := len(t.ExtendedUaf)
		extendedUafOffsets := make([]flatbuffers.UOffsetT, extendedUafLength)
		for j := 0; j < extendedUafLength; j++ {
			extendedUafOffsets[j] = t.ExtendedUaf[j].Pack(builder)
		}
		DdrdRawStartExtendedUafVector(builder, extendedUafLength)
		for j := extendedUafLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(extendedUafOffsets[j])
		}
		extendedUafOffset = builder.EndVector(extendedUafLength)
	}
	DdrdRawStart(builder)
	DdrdRawAddUafPairs(builder, uafPairsOffset)
	DdrdRawAddExtendedUaf(builder, extendedUafOffset)
	return DdrdRawEnd(builder)
}

func (rcv *DdrdRaw) UnPackTo(t *DdrdRawT) {
	uafPairsLength := rcv.UafPairsLength()
	t.UafPairs = make([]*DdrdUafPairRawT, uafPairsLength)
	for j := 0; j < uafPairsLength; j++ {
		x := DdrdUafPairRaw{}
		rcv.UafPairs(&x, j)
		t.UafPairs[j] = x.UnPack()
	}
	extendedUafLength := rcv.ExtendedUafLength()
	t.ExtendedUaf = make([]*DdrdExtendedUafPairRawT, extendedUafLength)
	for j := 0; j < extendedUafLength; j++ {
		x := DdrdExtendedUafPairRaw{}
		rcv.ExtendedUaf(&x, j)
		t.ExtendedUaf[j] = x.UnPack()
	}
}

func (rcv *DdrdRaw) UnPack() *DdrdRawT {
	if rcv == nil {
		return nil
	}
	t := &DdrdRawT{}
	rcv.UnPackTo(t)
	return t
}

type DdrdRaw struct {
	_tab flatbuffers.Table
}

func GetRootAsDdrdRaw(buf []byte, offset flatbuffers.UOffsetT) *DdrdRaw {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DdrdRaw{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDdrdRaw(buf []byte, offset flatbuffers.UOffsetT) *DdrdRaw {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DdrdRaw{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DdrdRaw) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DdrdRaw) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DdrdRaw) UafPairs(obj *DdrdUafPairRaw, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DdrdRaw) UafPairsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DdrdRaw) ExtendedUaf(obj *DdrdExtendedUafPairRaw, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DdrdRaw) ExtendedUafLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func DdrdRawStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DdrdRawAddUafPairs(builder *flatbuffers.Builder, uafPairs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(uafPairs), 0)
}
func DdrdRawStartUafPairsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DdrdRawAddExtendedUaf(builder *flatbuffers.Builder, extendedUaf flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(extendedUaf), 0)
}
func DdrdRawStartExtendedUafVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DdrdRawEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
