// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DdrdExtendedUafPairRawT struct {
	Basic *DdrdUafPairRawT `json:"basic"`
	UseThreadHistoryCount uint32 `json:"use_thread_history_count"`
	FreeThreadHistoryCount uint32 `json:"free_thread_history_count"`
	UseTargetTime uint64 `json:"use_target_time"`
	FreeTargetTime uint64 `json:"free_target_time"`
	PathDistanceUse float64 `json:"path_distance_use"`
	PathDistanceFree float64 `json:"path_distance_free"`
	AccessHistory []*DdrdSerializedAccessRawT `json:"access_history"`
}

func (t *DdrdExtendedUafPairRawT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	basicOffset := t.Basic.Pack(builder)
	accessHistoryOffset := flatbuffers.UOffsetT(0)
	if t.AccessHistory != nil {
		accessHistoryLength := len(t.AccessHistory)
		accessHistoryOffsets := make([]flatbuffers.UOffsetT, accessHistoryLength)
		for j := 0; j < accessHistoryLength; j++ {
			accessHistoryOffsets[j] = t.AccessHistory[j].Pack(builder)
		}
		DdrdExtendedUafPairRawStartAccessHistoryVector(builder, accessHistoryLength)
		for j := accessHistoryLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(accessHistoryOffsets[j])
		}
		accessHistoryOffset = builder.EndVector(accessHistoryLength)
	}
	DdrdExtendedUafPairRawStart(builder)
	DdrdExtendedUafPairRawAddBasic(builder, basicOffset)
	DdrdExtendedUafPairRawAddUseThreadHistoryCount(builder, t.UseThreadHistoryCount)
	DdrdExtendedUafPairRawAddFreeThreadHistoryCount(builder, t.FreeThreadHistoryCount)
	DdrdExtendedUafPairRawAddUseTargetTime(builder, t.UseTargetTime)
	DdrdExtendedUafPairRawAddFreeTargetTime(builder, t.FreeTargetTime)
	DdrdExtendedUafPairRawAddPathDistanceUse(builder, t.PathDistanceUse)
	DdrdExtendedUafPairRawAddPathDistanceFree(builder, t.PathDistanceFree)
	DdrdExtendedUafPairRawAddAccessHistory(builder, accessHistoryOffset)
	return DdrdExtendedUafPairRawEnd(builder)
}

func (rcv *DdrdExtendedUafPairRaw) UnPackTo(t *DdrdExtendedUafPairRawT) {
	t.Basic = rcv.Basic(nil).UnPack()
	t.UseThreadHistoryCount = rcv.UseThreadHistoryCount()
	t.FreeThreadHistoryCount = rcv.FreeThreadHistoryCount()
	t.UseTargetTime = rcv.UseTargetTime()
	t.FreeTargetTime = rcv.FreeTargetTime()
	t.PathDistanceUse = rcv.PathDistanceUse()
	t.PathDistanceFree = rcv.PathDistanceFree()
	accessHistoryLength := rcv.AccessHistoryLength()
	t.AccessHistory = make([]*DdrdSerializedAccessRawT, accessHistoryLength)
	for j := 0; j < accessHistoryLength; j++ {
		x := DdrdSerializedAccessRaw{}
		rcv.AccessHistory(&x, j)
		t.AccessHistory[j] = x.UnPack()
	}
}

func (rcv *DdrdExtendedUafPairRaw) UnPack() *DdrdExtendedUafPairRawT {
	if rcv == nil { return nil }
	t := &DdrdExtendedUafPairRawT{}
	rcv.UnPackTo(t)
	return t
}

type DdrdExtendedUafPairRaw struct {
	_tab flatbuffers.Table
}

func GetRootAsDdrdExtendedUafPairRaw(buf []byte, offset flatbuffers.UOffsetT) *DdrdExtendedUafPairRaw {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DdrdExtendedUafPairRaw{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDdrdExtendedUafPairRaw(buf []byte, offset flatbuffers.UOffsetT) *DdrdExtendedUafPairRaw {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DdrdExtendedUafPairRaw{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DdrdExtendedUafPairRaw) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DdrdExtendedUafPairRaw) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DdrdExtendedUafPairRaw) Basic(obj *DdrdUafPairRaw) *DdrdUafPairRaw {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DdrdUafPairRaw)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DdrdExtendedUafPairRaw) UseThreadHistoryCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdExtendedUafPairRaw) MutateUseThreadHistoryCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *DdrdExtendedUafPairRaw) FreeThreadHistoryCount() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdExtendedUafPairRaw) MutateFreeThreadHistoryCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *DdrdExtendedUafPairRaw) UseTargetTime() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdExtendedUafPairRaw) MutateUseTargetTime(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *DdrdExtendedUafPairRaw) FreeTargetTime() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdExtendedUafPairRaw) MutateFreeTargetTime(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *DdrdExtendedUafPairRaw) PathDistanceUse() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *DdrdExtendedUafPairRaw) MutatePathDistanceUse(n float64) bool {
	return rcv._tab.MutateFloat64Slot(14, n)
}

func (rcv *DdrdExtendedUafPairRaw) PathDistanceFree() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *DdrdExtendedUafPairRaw) MutatePathDistanceFree(n float64) bool {
	return rcv._tab.MutateFloat64Slot(16, n)
}

func (rcv *DdrdExtendedUafPairRaw) AccessHistory(obj *DdrdSerializedAccessRaw, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *DdrdExtendedUafPairRaw) AccessHistoryLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func DdrdExtendedUafPairRawStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func DdrdExtendedUafPairRawAddBasic(builder *flatbuffers.Builder, basic flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(basic), 0)
}
func DdrdExtendedUafPairRawAddUseThreadHistoryCount(builder *flatbuffers.Builder, useThreadHistoryCount uint32) {
	builder.PrependUint32Slot(1, useThreadHistoryCount, 0)
}
func DdrdExtendedUafPairRawAddFreeThreadHistoryCount(builder *flatbuffers.Builder, freeThreadHistoryCount uint32) {
	builder.PrependUint32Slot(2, freeThreadHistoryCount, 0)
}
func DdrdExtendedUafPairRawAddUseTargetTime(builder *flatbuffers.Builder, useTargetTime uint64) {
	builder.PrependUint64Slot(3, useTargetTime, 0)
}
func DdrdExtendedUafPairRawAddFreeTargetTime(builder *flatbuffers.Builder, freeTargetTime uint64) {
	builder.PrependUint64Slot(4, freeTargetTime, 0)
}
func DdrdExtendedUafPairRawAddPathDistanceUse(builder *flatbuffers.Builder, pathDistanceUse float64) {
	builder.PrependFloat64Slot(5, pathDistanceUse, 0.0)
}
func DdrdExtendedUafPairRawAddPathDistanceFree(builder *flatbuffers.Builder, pathDistanceFree float64) {
	builder.PrependFloat64Slot(6, pathDistanceFree, 0.0)
}
func DdrdExtendedUafPairRawAddAccessHistory(builder *flatbuffers.Builder, accessHistory flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(accessHistory), 0)
}
func DdrdExtendedUafPairRawStartAccessHistoryVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DdrdExtendedUafPairRawEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
