// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DdrdUafPairRawT struct {
	FreeAccessName uint64 `json:"free_access_name"`
	UseAccessName uint64 `json:"use_access_name"`
	FreeCallStack uint64 `json:"free_call_stack"`
	UseCallStack uint64 `json:"use_call_stack"`
	Signal uint64 `json:"signal"`
	TimeDiff uint64 `json:"time_diff"`
	FreeSn int32 `json:"free_sn"`
	UseSn int32 `json:"use_sn"`
	LockType uint32 `json:"lock_type"`
	UseAccessType uint32 `json:"use_access_type"`
}

func (t *DdrdUafPairRawT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	DdrdUafPairRawStart(builder)
	DdrdUafPairRawAddFreeAccessName(builder, t.FreeAccessName)
	DdrdUafPairRawAddUseAccessName(builder, t.UseAccessName)
	DdrdUafPairRawAddFreeCallStack(builder, t.FreeCallStack)
	DdrdUafPairRawAddUseCallStack(builder, t.UseCallStack)
	DdrdUafPairRawAddSignal(builder, t.Signal)
	DdrdUafPairRawAddTimeDiff(builder, t.TimeDiff)
	DdrdUafPairRawAddFreeSn(builder, t.FreeSn)
	DdrdUafPairRawAddUseSn(builder, t.UseSn)
	DdrdUafPairRawAddLockType(builder, t.LockType)
	DdrdUafPairRawAddUseAccessType(builder, t.UseAccessType)
	return DdrdUafPairRawEnd(builder)
}

func (rcv *DdrdUafPairRaw) UnPackTo(t *DdrdUafPairRawT) {
	t.FreeAccessName = rcv.FreeAccessName()
	t.UseAccessName = rcv.UseAccessName()
	t.FreeCallStack = rcv.FreeCallStack()
	t.UseCallStack = rcv.UseCallStack()
	t.Signal = rcv.Signal()
	t.TimeDiff = rcv.TimeDiff()
	t.FreeSn = rcv.FreeSn()
	t.UseSn = rcv.UseSn()
	t.LockType = rcv.LockType()
	t.UseAccessType = rcv.UseAccessType()
}

func (rcv *DdrdUafPairRaw) UnPack() *DdrdUafPairRawT {
	if rcv == nil { return nil }
	t := &DdrdUafPairRawT{}
	rcv.UnPackTo(t)
	return t
}

type DdrdUafPairRaw struct {
	_tab flatbuffers.Table
}

func GetRootAsDdrdUafPairRaw(buf []byte, offset flatbuffers.UOffsetT) *DdrdUafPairRaw {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DdrdUafPairRaw{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDdrdUafPairRaw(buf []byte, offset flatbuffers.UOffsetT) *DdrdUafPairRaw {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DdrdUafPairRaw{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DdrdUafPairRaw) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DdrdUafPairRaw) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DdrdUafPairRaw) FreeAccessName() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdUafPairRaw) MutateFreeAccessName(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *DdrdUafPairRaw) UseAccessName() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdUafPairRaw) MutateUseAccessName(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *DdrdUafPairRaw) FreeCallStack() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdUafPairRaw) MutateFreeCallStack(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *DdrdUafPairRaw) UseCallStack() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdUafPairRaw) MutateUseCallStack(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *DdrdUafPairRaw) Signal() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdUafPairRaw) MutateSignal(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *DdrdUafPairRaw) TimeDiff() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdUafPairRaw) MutateTimeDiff(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func (rcv *DdrdUafPairRaw) FreeSn() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdUafPairRaw) MutateFreeSn(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

func (rcv *DdrdUafPairRaw) UseSn() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdUafPairRaw) MutateUseSn(n int32) bool {
	return rcv._tab.MutateInt32Slot(18, n)
}

func (rcv *DdrdUafPairRaw) LockType() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdUafPairRaw) MutateLockType(n uint32) bool {
	return rcv._tab.MutateUint32Slot(20, n)
}

func (rcv *DdrdUafPairRaw) UseAccessType() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdUafPairRaw) MutateUseAccessType(n uint32) bool {
	return rcv._tab.MutateUint32Slot(22, n)
}

func DdrdUafPairRawStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func DdrdUafPairRawAddFreeAccessName(builder *flatbuffers.Builder, freeAccessName uint64) {
	builder.PrependUint64Slot(0, freeAccessName, 0)
}
func DdrdUafPairRawAddUseAccessName(builder *flatbuffers.Builder, useAccessName uint64) {
	builder.PrependUint64Slot(1, useAccessName, 0)
}
func DdrdUafPairRawAddFreeCallStack(builder *flatbuffers.Builder, freeCallStack uint64) {
	builder.PrependUint64Slot(2, freeCallStack, 0)
}
func DdrdUafPairRawAddUseCallStack(builder *flatbuffers.Builder, useCallStack uint64) {
	builder.PrependUint64Slot(3, useCallStack, 0)
}
func DdrdUafPairRawAddSignal(builder *flatbuffers.Builder, signal uint64) {
	builder.PrependUint64Slot(4, signal, 0)
}
func DdrdUafPairRawAddTimeDiff(builder *flatbuffers.Builder, timeDiff uint64) {
	builder.PrependUint64Slot(5, timeDiff, 0)
}
func DdrdUafPairRawAddFreeSn(builder *flatbuffers.Builder, freeSn int32) {
	builder.PrependInt32Slot(6, freeSn, 0)
}
func DdrdUafPairRawAddUseSn(builder *flatbuffers.Builder, useSn int32) {
	builder.PrependInt32Slot(7, useSn, 0)
}
func DdrdUafPairRawAddLockType(builder *flatbuffers.Builder, lockType uint32) {
	builder.PrependUint32Slot(8, lockType, 0)
}
func DdrdUafPairRawAddUseAccessType(builder *flatbuffers.Builder, useAccessType uint32) {
	builder.PrependUint32Slot(9, useAccessType, 0)
}
func DdrdUafPairRawEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
