// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DdrdSerializedAccessRawT struct {
	VarName       uint64 `json:"var_name"`
	CallStackHash uint64 `json:"call_stack_hash"`
	AccessTime    uint64 `json:"access_time"`
	Sn            uint32 `json:"sn"`
	AccessType    uint32 `json:"access_type"`
}

func (t *DdrdSerializedAccessRawT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	DdrdSerializedAccessRawStart(builder)
	DdrdSerializedAccessRawAddVarName(builder, t.VarName)
	DdrdSerializedAccessRawAddCallStackHash(builder, t.CallStackHash)
	DdrdSerializedAccessRawAddAccessTime(builder, t.AccessTime)
	DdrdSerializedAccessRawAddSn(builder, t.Sn)
	DdrdSerializedAccessRawAddAccessType(builder, t.AccessType)
	return DdrdSerializedAccessRawEnd(builder)
}

func (rcv *DdrdSerializedAccessRaw) UnPackTo(t *DdrdSerializedAccessRawT) {
	t.VarName = rcv.VarName()
	t.CallStackHash = rcv.CallStackHash()
	t.AccessTime = rcv.AccessTime()
	t.Sn = rcv.Sn()
	t.AccessType = rcv.AccessType()
}

func (rcv *DdrdSerializedAccessRaw) UnPack() *DdrdSerializedAccessRawT {
	if rcv == nil {
		return nil
	}
	t := &DdrdSerializedAccessRawT{}
	rcv.UnPackTo(t)
	return t
}

type DdrdSerializedAccessRaw struct {
	_tab flatbuffers.Table
}

func GetRootAsDdrdSerializedAccessRaw(buf []byte, offset flatbuffers.UOffsetT) *DdrdSerializedAccessRaw {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DdrdSerializedAccessRaw{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDdrdSerializedAccessRaw(buf []byte, offset flatbuffers.UOffsetT) *DdrdSerializedAccessRaw {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DdrdSerializedAccessRaw{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DdrdSerializedAccessRaw) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DdrdSerializedAccessRaw) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DdrdSerializedAccessRaw) VarName() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdSerializedAccessRaw) MutateVarName(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *DdrdSerializedAccessRaw) CallStackHash() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdSerializedAccessRaw) MutateCallStackHash(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *DdrdSerializedAccessRaw) AccessTime() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdSerializedAccessRaw) MutateAccessTime(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *DdrdSerializedAccessRaw) Sn() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdSerializedAccessRaw) MutateSn(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func (rcv *DdrdSerializedAccessRaw) AccessType() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DdrdSerializedAccessRaw) MutateAccessType(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func DdrdSerializedAccessRawStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func DdrdSerializedAccessRawAddVarName(builder *flatbuffers.Builder, varName uint64) {
	builder.PrependUint64Slot(0, varName, 0)
}
func DdrdSerializedAccessRawAddCallStackHash(builder *flatbuffers.Builder, callStackHash uint64) {
	builder.PrependUint64Slot(1, callStackHash, 0)
}
func DdrdSerializedAccessRawAddAccessTime(builder *flatbuffers.Builder, accessTime uint64) {
	builder.PrependUint64Slot(2, accessTime, 0)
}
func DdrdSerializedAccessRawAddSn(builder *flatbuffers.Builder, sn uint32) {
	builder.PrependUint32Slot(3, sn, 0)
}
func DdrdSerializedAccessRawAddAccessType(builder *flatbuffers.Builder, accessType uint32) {
	builder.PrependUint32Slot(4, accessType, 0)
}
func DdrdSerializedAccessRawEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
