// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	"strconv"

	flatbuffers "github.com/google/flatbuffers/go"
)

type ExecutorMessagesRaw byte

const (
	ExecutorMessagesRawNONE       ExecutorMessagesRaw = 0
	ExecutorMessagesRawExecResult ExecutorMessagesRaw = 1
	ExecutorMessagesRawExecuting  ExecutorMessagesRaw = 2
	ExecutorMessagesRawState      ExecutorMessagesRaw = 3
)

var EnumNamesExecutorMessagesRaw = map[ExecutorMessagesRaw]string{
	ExecutorMessagesRawNONE:       "NONE",
	ExecutorMessagesRawExecResult: "ExecResult",
	ExecutorMessagesRawExecuting:  "Executing",
	ExecutorMessagesRawState:      "State",
}

var EnumValuesExecutorMessagesRaw = map[string]ExecutorMessagesRaw{
	"NONE":       ExecutorMessagesRawNONE,
	"ExecResult": ExecutorMessagesRawExecResult,
	"Executing":  ExecutorMessagesRawExecuting,
	"State":      ExecutorMessagesRawState,
}

func (v ExecutorMessagesRaw) String() string {
	if s, ok := EnumNamesExecutorMessagesRaw[v]; ok {
		return s
	}
	return "ExecutorMessagesRaw(" + strconv.FormatInt(int64(v), 10) + ")"
}

type ExecutorMessagesRawT struct {
	Type  ExecutorMessagesRaw
	Value interface{}
}

func (t *ExecutorMessagesRawT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	switch t.Type {
	case ExecutorMessagesRawExecResult:
		return t.Value.(*ExecResultRawT).Pack(builder)
	case ExecutorMessagesRawExecuting:
		return t.Value.(*ExecutingMessageRawT).Pack(builder)
	case ExecutorMessagesRawState:
		return t.Value.(*StateResultRawT).Pack(builder)
	}
	return 0
}

func (rcv ExecutorMessagesRaw) UnPack(table flatbuffers.Table) *ExecutorMessagesRawT {
	switch rcv {
	case ExecutorMessagesRawExecResult:
		x := ExecResultRaw{_tab: table}
		return &ExecutorMessagesRawT{Type: ExecutorMessagesRawExecResult, Value: x.UnPack()}
	case ExecutorMessagesRawExecuting:
		x := ExecutingMessageRaw{_tab: table}
		return &ExecutorMessagesRawT{Type: ExecutorMessagesRawExecuting, Value: x.UnPack()}
	case ExecutorMessagesRawState:
		x := StateResultRaw{_tab: table}
		return &ExecutorMessagesRawT{Type: ExecutorMessagesRawState, Value: x.UnPack()}
	}
	return nil
}
