// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import "strconv"

type ExecFlag uint64

const (
	ExecFlagCollectSignal       ExecFlag = 1
	ExecFlagCollectCover        ExecFlag = 2
	ExecFlagDedupCover          ExecFlag = 4
	ExecFlagCollectComps        ExecFlag = 8
	ExecFlagThreaded            ExecFlag = 16
	ExecFlagBarrier             ExecFlag = 32
	ExecFlagCollectDdrdUaf      ExecFlag = 64
	ExecFlagCollectDdrdRace     ExecFlag = 128
	ExecFlagCollectDdrdExtended ExecFlag = 256
)

var EnumNamesExecFlag = map[ExecFlag]string{
	ExecFlagCollectSignal:       "CollectSignal",
	ExecFlagCollectCover:        "CollectCover",
	ExecFlagDedupCover:          "DedupCover",
	ExecFlagCollectComps:        "CollectComps",
	ExecFlagThreaded:            "Threaded",
	ExecFlagBarrier:             "Barrier",
	ExecFlagCollectDdrdUaf:      "CollectDdrdUaf",
	ExecFlagCollectDdrdRace:     "CollectDdrdRace",
	ExecFlagCollectDdrdExtended: "CollectDdrdExtended",
}

var EnumValuesExecFlag = map[string]ExecFlag{
	"CollectSignal":       ExecFlagCollectSignal,
	"CollectCover":        ExecFlagCollectCover,
	"DedupCover":          ExecFlagDedupCover,
	"CollectComps":        ExecFlagCollectComps,
	"Threaded":            ExecFlagThreaded,
	"Barrier":             ExecFlagBarrier,
	"CollectDdrdUaf":      ExecFlagCollectDdrdUaf,
	"CollectDdrdRace":     ExecFlagCollectDdrdRace,
	"CollectDdrdExtended": ExecFlagCollectDdrdExtended,
}

func (v ExecFlag) String() string {
	if s, ok := EnumNamesExecFlag[v]; ok {
		return s
	}
	return "ExecFlag(" + strconv.FormatInt(int64(v), 10) + ")"
}
