// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ExecRequestRawT struct {
	Id int64 `json:"id"`
	Type RequestType `json:"type"`
	Avoid uint64 `json:"avoid"`
	Data []byte `json:"data"`
	ExecOpts *ExecOptsRawT `json:"exec_opts"`
	Flags RequestFlag `json:"flags"`
	AllSignal []int32 `json:"all_signal"`
	BarrierParticipants uint64 `json:"barrier_participants"`
	BarrierGroupId int64 `json:"barrier_group_id"`
	BarrierIndex int32 `json:"barrier_index"`
	BarrierGroupSize int32 `json:"barrier_group_size"`
	BarrierStartDelayUs []int64 `json:"barrier_start_delay_us"`
	UkcUseName uint64 `json:"ukc_use_name"`
	UkcUseStack uint64 `json:"ukc_use_stack"`
	UkcFreeName uint64 `json:"ukc_free_name"`
	UkcFreeStack uint64 `json:"ukc_free_stack"`
	UkcUseAccessDelayTime int32 `json:"ukc_use_access_delay_time"`
	UkcIsValid bool `json:"ukc_is_valid"`
}

func (t *ExecRequestRawT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	dataOffset := flatbuffers.UOffsetT(0)
	if t.Data != nil {
		dataOffset = builder.CreateByteString(t.Data)
	}
	allSignalOffset := flatbuffers.UOffsetT(0)
	if t.AllSignal != nil {
		allSignalLength := len(t.AllSignal)
		ExecRequestRawStartAllSignalVector(builder, allSignalLength)
		for j := allSignalLength - 1; j >= 0; j-- {
			builder.PrependInt32(t.AllSignal[j])
		}
		allSignalOffset = builder.EndVector(allSignalLength)
	}
	barrierStartDelayUsOffset := flatbuffers.UOffsetT(0)
	if t.BarrierStartDelayUs != nil {
		barrierStartDelayUsLength := len(t.BarrierStartDelayUs)
		ExecRequestRawStartBarrierStartDelayUsVector(builder, barrierStartDelayUsLength)
		for j := barrierStartDelayUsLength - 1; j >= 0; j-- {
			builder.PrependInt64(t.BarrierStartDelayUs[j])
		}
		barrierStartDelayUsOffset = builder.EndVector(barrierStartDelayUsLength)
	}
	ExecRequestRawStart(builder)
	ExecRequestRawAddId(builder, t.Id)
	ExecRequestRawAddType(builder, t.Type)
	ExecRequestRawAddAvoid(builder, t.Avoid)
	ExecRequestRawAddData(builder, dataOffset)
	execOptsOffset := t.ExecOpts.Pack(builder)
	ExecRequestRawAddExecOpts(builder, execOptsOffset)
	ExecRequestRawAddFlags(builder, t.Flags)
	ExecRequestRawAddAllSignal(builder, allSignalOffset)
	ExecRequestRawAddBarrierParticipants(builder, t.BarrierParticipants)
	ExecRequestRawAddBarrierGroupId(builder, t.BarrierGroupId)
	ExecRequestRawAddBarrierIndex(builder, t.BarrierIndex)
	ExecRequestRawAddBarrierGroupSize(builder, t.BarrierGroupSize)
	ExecRequestRawAddBarrierStartDelayUs(builder, barrierStartDelayUsOffset)
	ExecRequestRawAddUkcUseName(builder, t.UkcUseName)
	ExecRequestRawAddUkcUseStack(builder, t.UkcUseStack)
	ExecRequestRawAddUkcFreeName(builder, t.UkcFreeName)
	ExecRequestRawAddUkcFreeStack(builder, t.UkcFreeStack)
	ExecRequestRawAddUkcUseAccessDelayTime(builder, t.UkcUseAccessDelayTime)
	ExecRequestRawAddUkcIsValid(builder, t.UkcIsValid)
	return ExecRequestRawEnd(builder)
}

func (rcv *ExecRequestRaw) UnPackTo(t *ExecRequestRawT) {
	t.Id = rcv.Id()
	t.Type = rcv.Type()
	t.Avoid = rcv.Avoid()
	t.Data = rcv.DataBytes()
	t.ExecOpts = rcv.ExecOpts(nil).UnPack()
	t.Flags = rcv.Flags()
	allSignalLength := rcv.AllSignalLength()
	t.AllSignal = make([]int32, allSignalLength)
	for j := 0; j < allSignalLength; j++ {
		t.AllSignal[j] = rcv.AllSignal(j)
	}
	t.BarrierParticipants = rcv.BarrierParticipants()
	t.BarrierGroupId = rcv.BarrierGroupId()
	t.BarrierIndex = rcv.BarrierIndex()
	t.BarrierGroupSize = rcv.BarrierGroupSize()
	barrierStartDelayUsLength := rcv.BarrierStartDelayUsLength()
	t.BarrierStartDelayUs = make([]int64, barrierStartDelayUsLength)
	for j := 0; j < barrierStartDelayUsLength; j++ {
		t.BarrierStartDelayUs[j] = rcv.BarrierStartDelayUs(j)
	}
	t.UkcUseName = rcv.UkcUseName()
	t.UkcUseStack = rcv.UkcUseStack()
	t.UkcFreeName = rcv.UkcFreeName()
	t.UkcFreeStack = rcv.UkcFreeStack()
	t.UkcUseAccessDelayTime = rcv.UkcUseAccessDelayTime()
	t.UkcIsValid = rcv.UkcIsValid()
}

func (rcv *ExecRequestRaw) UnPack() *ExecRequestRawT {
	if rcv == nil { return nil }
	t := &ExecRequestRawT{}
	rcv.UnPackTo(t)
	return t
}

type ExecRequestRaw struct {
	_tab flatbuffers.Table
}

func GetRootAsExecRequestRaw(buf []byte, offset flatbuffers.UOffsetT) *ExecRequestRaw {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ExecRequestRaw{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsExecRequestRaw(buf []byte, offset flatbuffers.UOffsetT) *ExecRequestRaw {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ExecRequestRaw{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ExecRequestRaw) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ExecRequestRaw) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ExecRequestRaw) Id() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExecRequestRaw) MutateId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *ExecRequestRaw) Type() RequestType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return RequestType(rcv._tab.GetUint64(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ExecRequestRaw) MutateType(n RequestType) bool {
	return rcv._tab.MutateUint64Slot(6, uint64(n))
}

func (rcv *ExecRequestRaw) Avoid() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExecRequestRaw) MutateAvoid(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *ExecRequestRaw) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ExecRequestRaw) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ExecRequestRaw) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ExecRequestRaw) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ExecRequestRaw) ExecOpts(obj *ExecOptsRaw) *ExecOptsRaw {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := o + rcv._tab.Pos
		if obj == nil {
			obj = new(ExecOptsRaw)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ExecRequestRaw) Flags() RequestFlag {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return RequestFlag(rcv._tab.GetUint64(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ExecRequestRaw) MutateFlags(n RequestFlag) bool {
	return rcv._tab.MutateUint64Slot(14, uint64(n))
}

func (rcv *ExecRequestRaw) AllSignal(j int) int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *ExecRequestRaw) AllSignalLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ExecRequestRaw) MutateAllSignal(j int, n int32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *ExecRequestRaw) BarrierParticipants() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExecRequestRaw) MutateBarrierParticipants(n uint64) bool {
	return rcv._tab.MutateUint64Slot(18, n)
}

func (rcv *ExecRequestRaw) BarrierGroupId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExecRequestRaw) MutateBarrierGroupId(n int64) bool {
	return rcv._tab.MutateInt64Slot(20, n)
}

func (rcv *ExecRequestRaw) BarrierIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExecRequestRaw) MutateBarrierIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(22, n)
}

func (rcv *ExecRequestRaw) BarrierGroupSize() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExecRequestRaw) MutateBarrierGroupSize(n int32) bool {
	return rcv._tab.MutateInt32Slot(24, n)
}

func (rcv *ExecRequestRaw) BarrierStartDelayUs(j int) int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *ExecRequestRaw) BarrierStartDelayUsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ExecRequestRaw) MutateBarrierStartDelayUs(j int, n int64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func (rcv *ExecRequestRaw) UkcUseName() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExecRequestRaw) MutateUkcUseName(n uint64) bool {
	return rcv._tab.MutateUint64Slot(28, n)
}

func (rcv *ExecRequestRaw) UkcUseStack() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExecRequestRaw) MutateUkcUseStack(n uint64) bool {
	return rcv._tab.MutateUint64Slot(30, n)
}

func (rcv *ExecRequestRaw) UkcFreeName() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExecRequestRaw) MutateUkcFreeName(n uint64) bool {
	return rcv._tab.MutateUint64Slot(32, n)
}

func (rcv *ExecRequestRaw) UkcFreeStack() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExecRequestRaw) MutateUkcFreeStack(n uint64) bool {
	return rcv._tab.MutateUint64Slot(34, n)
}

func (rcv *ExecRequestRaw) UkcUseAccessDelayTime() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExecRequestRaw) MutateUkcUseAccessDelayTime(n int32) bool {
	return rcv._tab.MutateInt32Slot(36, n)
}

func (rcv *ExecRequestRaw) UkcIsValid() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ExecRequestRaw) MutateUkcIsValid(n bool) bool {
	return rcv._tab.MutateBoolSlot(38, n)
}

func ExecRequestRawStart(builder *flatbuffers.Builder) {
	builder.StartObject(18)
}
func ExecRequestRawAddId(builder *flatbuffers.Builder, id int64) {
	builder.PrependInt64Slot(0, id, 0)
}
func ExecRequestRawAddType(builder *flatbuffers.Builder, type_ RequestType) {
	builder.PrependUint64Slot(1, uint64(type_), 0)
}
func ExecRequestRawAddAvoid(builder *flatbuffers.Builder, avoid uint64) {
	builder.PrependUint64Slot(2, avoid, 0)
}
func ExecRequestRawAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(data), 0)
}
func ExecRequestRawStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ExecRequestRawAddExecOpts(builder *flatbuffers.Builder, execOpts flatbuffers.UOffsetT) {
	builder.PrependStructSlot(4, flatbuffers.UOffsetT(execOpts), 0)
}
func ExecRequestRawAddFlags(builder *flatbuffers.Builder, flags RequestFlag) {
	builder.PrependUint64Slot(5, uint64(flags), 0)
}
func ExecRequestRawAddAllSignal(builder *flatbuffers.Builder, allSignal flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(allSignal), 0)
}
func ExecRequestRawStartAllSignalVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ExecRequestRawAddBarrierParticipants(builder *flatbuffers.Builder, barrierParticipants uint64) {
	builder.PrependUint64Slot(7, barrierParticipants, 0)
}
func ExecRequestRawAddBarrierGroupId(builder *flatbuffers.Builder, barrierGroupId int64) {
	builder.PrependInt64Slot(8, barrierGroupId, 0)
}
func ExecRequestRawAddBarrierIndex(builder *flatbuffers.Builder, barrierIndex int32) {
	builder.PrependInt32Slot(9, barrierIndex, 0)
}
func ExecRequestRawAddBarrierGroupSize(builder *flatbuffers.Builder, barrierGroupSize int32) {
	builder.PrependInt32Slot(10, barrierGroupSize, 0)
}
func ExecRequestRawAddBarrierStartDelayUs(builder *flatbuffers.Builder, barrierStartDelayUs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(barrierStartDelayUs), 0)
}
func ExecRequestRawStartBarrierStartDelayUsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func ExecRequestRawAddUkcUseName(builder *flatbuffers.Builder, ukcUseName uint64) {
	builder.PrependUint64Slot(12, ukcUseName, 0)
}
func ExecRequestRawAddUkcUseStack(builder *flatbuffers.Builder, ukcUseStack uint64) {
	builder.PrependUint64Slot(13, ukcUseStack, 0)
}
func ExecRequestRawAddUkcFreeName(builder *flatbuffers.Builder, ukcFreeName uint64) {
	builder.PrependUint64Slot(14, ukcFreeName, 0)
}
func ExecRequestRawAddUkcFreeStack(builder *flatbuffers.Builder, ukcFreeStack uint64) {
	builder.PrependUint64Slot(15, ukcFreeStack, 0)
}
func ExecRequestRawAddUkcUseAccessDelayTime(builder *flatbuffers.Builder, ukcUseAccessDelayTime int32) {
	builder.PrependInt32Slot(16, ukcUseAccessDelayTime, 0)
}
func ExecRequestRawAddUkcIsValid(builder *flatbuffers.Builder, ukcIsValid bool) {
	builder.PrependBoolSlot(17, ukcIsValid, false)
}
func ExecRequestRawEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
