// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ExecOptsRawT struct {
	EnvFlags ExecEnv `json:"env_flags"`
	ExecFlags ExecFlag `json:"exec_flags"`
	SandboxArg int64 `json:"sandbox_arg"`
}

func (t *ExecOptsRawT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	return CreateExecOptsRaw(builder, t.EnvFlags, t.ExecFlags, t.SandboxArg)
}
func (rcv *ExecOptsRaw) UnPackTo(t *ExecOptsRawT) {
	t.EnvFlags = rcv.EnvFlags()
	t.ExecFlags = rcv.ExecFlags()
	t.SandboxArg = rcv.SandboxArg()
}

func (rcv *ExecOptsRaw) UnPack() *ExecOptsRawT {
	if rcv == nil { return nil }
	t := &ExecOptsRawT{}
	rcv.UnPackTo(t)
	return t
}

type ExecOptsRaw struct {
	_tab flatbuffers.Struct
}

func (rcv *ExecOptsRaw) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ExecOptsRaw) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *ExecOptsRaw) EnvFlags() ExecEnv {
	return ExecEnv(rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0)))
}
func (rcv *ExecOptsRaw) MutateEnvFlags(n ExecEnv) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), uint64(n))
}

func (rcv *ExecOptsRaw) ExecFlags() ExecFlag {
	return ExecFlag(rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(8)))
}
func (rcv *ExecOptsRaw) MutateExecFlags(n ExecFlag) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(8), uint64(n))
}

func (rcv *ExecOptsRaw) SandboxArg() int64 {
	return rcv._tab.GetInt64(rcv._tab.Pos + flatbuffers.UOffsetT(16))
}
func (rcv *ExecOptsRaw) MutateSandboxArg(n int64) bool {
	return rcv._tab.MutateInt64(rcv._tab.Pos+flatbuffers.UOffsetT(16), n)
}

func CreateExecOptsRaw(builder *flatbuffers.Builder, envFlags ExecEnv, execFlags ExecFlag, sandboxArg int64) flatbuffers.UOffsetT {
	builder.Prep(8, 24)
	builder.PrependInt64(sandboxArg)
	builder.PrependUint64(uint64(execFlags))
	builder.PrependUint64(uint64(envFlags))
	return builder.Offset()
}
