// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ExecResultRawT struct {
	Id int64 `json:"id"`
	Proc int32 `json:"proc"`
	Output []byte `json:"output"`
	Hanged bool `json:"hanged"`
	Error string `json:"error"`
	Info *ProgInfoRawT `json:"info"`
	BarrierProcs uint64 `json:"barrier_procs"`
	BarrierGroupId int64 `json:"barrier_group_id"`
	BarrierIndex int32 `json:"barrier_index"`
	BarrierGroupSize int32 `json:"barrier_group_size"`
}

func (t *ExecResultRawT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	outputOffset := flatbuffers.UOffsetT(0)
	if t.Output != nil {
		outputOffset = builder.CreateByteString(t.Output)
	}
	errorOffset := builder.CreateString(t.Error)
	infoOffset := t.Info.Pack(builder)
	ExecResultRawStart(builder)
	ExecResultRawAddId(builder, t.Id)
	ExecResultRawAddProc(builder, t.Proc)
	ExecResultRawAddOutput(builder, outputOffset)
	ExecResultRawAddHanged(builder, t.Hanged)
	ExecResultRawAddError(builder, errorOffset)
	ExecResultRawAddInfo(builder, infoOffset)
	ExecResultRawAddBarrierProcs(builder, t.BarrierProcs)
	ExecResultRawAddBarrierGroupId(builder, t.BarrierGroupId)
	ExecResultRawAddBarrierIndex(builder, t.BarrierIndex)
	ExecResultRawAddBarrierGroupSize(builder, t.BarrierGroupSize)
	return ExecResultRawEnd(builder)
}

func (rcv *ExecResultRaw) UnPackTo(t *ExecResultRawT) {
	t.Id = rcv.Id()
	t.Proc = rcv.Proc()
	t.Output = rcv.OutputBytes()
	t.Hanged = rcv.Hanged()
	t.Error = string(rcv.Error())
	t.Info = rcv.Info(nil).UnPack()
	t.BarrierProcs = rcv.BarrierProcs()
	t.BarrierGroupId = rcv.BarrierGroupId()
	t.BarrierIndex = rcv.BarrierIndex()
	t.BarrierGroupSize = rcv.BarrierGroupSize()
}

func (rcv *ExecResultRaw) UnPack() *ExecResultRawT {
	if rcv == nil { return nil }
	t := &ExecResultRawT{}
	rcv.UnPackTo(t)
	return t
}

type ExecResultRaw struct {
	_tab flatbuffers.Table
}

func GetRootAsExecResultRaw(buf []byte, offset flatbuffers.UOffsetT) *ExecResultRaw {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ExecResultRaw{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsExecResultRaw(buf []byte, offset flatbuffers.UOffsetT) *ExecResultRaw {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ExecResultRaw{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ExecResultRaw) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ExecResultRaw) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ExecResultRaw) Id() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExecResultRaw) MutateId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *ExecResultRaw) Proc() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExecResultRaw) MutateProc(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *ExecResultRaw) Output(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ExecResultRaw) OutputLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ExecResultRaw) OutputBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ExecResultRaw) MutateOutput(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ExecResultRaw) Hanged() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ExecResultRaw) MutateHanged(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *ExecResultRaw) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ExecResultRaw) Info(obj *ProgInfoRaw) *ProgInfoRaw {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ProgInfoRaw)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ExecResultRaw) BarrierProcs() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExecResultRaw) MutateBarrierProcs(n uint64) bool {
	return rcv._tab.MutateUint64Slot(16, n)
}

func (rcv *ExecResultRaw) BarrierGroupId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExecResultRaw) MutateBarrierGroupId(n int64) bool {
	return rcv._tab.MutateInt64Slot(18, n)
}

func (rcv *ExecResultRaw) BarrierIndex() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExecResultRaw) MutateBarrierIndex(n int32) bool {
	return rcv._tab.MutateInt32Slot(20, n)
}

func (rcv *ExecResultRaw) BarrierGroupSize() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ExecResultRaw) MutateBarrierGroupSize(n int32) bool {
	return rcv._tab.MutateInt32Slot(22, n)
}

func ExecResultRawStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func ExecResultRawAddId(builder *flatbuffers.Builder, id int64) {
	builder.PrependInt64Slot(0, id, 0)
}
func ExecResultRawAddProc(builder *flatbuffers.Builder, proc int32) {
	builder.PrependInt32Slot(1, proc, 0)
}
func ExecResultRawAddOutput(builder *flatbuffers.Builder, output flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(output), 0)
}
func ExecResultRawStartOutputVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ExecResultRawAddHanged(builder *flatbuffers.Builder, hanged bool) {
	builder.PrependBoolSlot(3, hanged, false)
}
func ExecResultRawAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(error), 0)
}
func ExecResultRawAddInfo(builder *flatbuffers.Builder, info flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(info), 0)
}
func ExecResultRawAddBarrierProcs(builder *flatbuffers.Builder, barrierProcs uint64) {
	builder.PrependUint64Slot(6, barrierProcs, 0)
}
func ExecResultRawAddBarrierGroupId(builder *flatbuffers.Builder, barrierGroupId int64) {
	builder.PrependInt64Slot(7, barrierGroupId, 0)
}
func ExecResultRawAddBarrierIndex(builder *flatbuffers.Builder, barrierIndex int32) {
	builder.PrependInt32Slot(8, barrierIndex, 0)
}
func ExecResultRawAddBarrierGroupSize(builder *flatbuffers.Builder, barrierGroupSize int32) {
	builder.PrependInt32Slot(9, barrierGroupSize, 0)
}
func ExecResultRawEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
