// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import "strconv"

type ExecEnv uint64

const (
	ExecEnvDebug               ExecEnv = 1
	ExecEnvSignal              ExecEnv = 2
	ExecEnvReadOnlyCoverage    ExecEnv = 4
	ExecEnvResetState          ExecEnv = 8
	ExecEnvSandboxNone         ExecEnv = 16
	ExecEnvSandboxSetuid       ExecEnv = 32
	ExecEnvSandboxNamespace    ExecEnv = 64
	ExecEnvSandboxAndroid      ExecEnv = 128
	ExecEnvExtraCover          ExecEnv = 256
	ExecEnvEnableTun           ExecEnv = 512
	ExecEnvEnableNetDev        ExecEnv = 1024
	ExecEnvEnableNetReset      ExecEnv = 2048
	ExecEnvEnableCgroups       ExecEnv = 4096
	ExecEnvEnableCloseFds      ExecEnv = 8192
	ExecEnvEnableDevlinkPCI    ExecEnv = 16384
	ExecEnvEnableVhciInjection ExecEnv = 32768
	ExecEnvEnableWifi          ExecEnv = 65536
	ExecEnvDelayKcovMmap       ExecEnv = 131072
	ExecEnvEnableNicVF         ExecEnv = 262144
	ExecEnvEnableDdrdMonitor   ExecEnv = 524288
)

var EnumNamesExecEnv = map[ExecEnv]string{
	ExecEnvDebug:               "Debug",
	ExecEnvSignal:              "Signal",
	ExecEnvReadOnlyCoverage:    "ReadOnlyCoverage",
	ExecEnvResetState:          "ResetState",
	ExecEnvSandboxNone:         "SandboxNone",
	ExecEnvSandboxSetuid:       "SandboxSetuid",
	ExecEnvSandboxNamespace:    "SandboxNamespace",
	ExecEnvSandboxAndroid:      "SandboxAndroid",
	ExecEnvExtraCover:          "ExtraCover",
	ExecEnvEnableTun:           "EnableTun",
	ExecEnvEnableNetDev:        "EnableNetDev",
	ExecEnvEnableNetReset:      "EnableNetReset",
	ExecEnvEnableCgroups:       "EnableCgroups",
	ExecEnvEnableCloseFds:      "EnableCloseFds",
	ExecEnvEnableDevlinkPCI:    "EnableDevlinkPCI",
	ExecEnvEnableVhciInjection: "EnableVhciInjection",
	ExecEnvEnableWifi:          "EnableWifi",
	ExecEnvDelayKcovMmap:       "DelayKcovMmap",
	ExecEnvEnableNicVF:         "EnableNicVF",
	ExecEnvEnableDdrdMonitor:   "EnableDdrdMonitor",
}

var EnumValuesExecEnv = map[string]ExecEnv{
	"Debug":               ExecEnvDebug,
	"Signal":              ExecEnvSignal,
	"ReadOnlyCoverage":    ExecEnvReadOnlyCoverage,
	"ResetState":          ExecEnvResetState,
	"SandboxNone":         ExecEnvSandboxNone,
	"SandboxSetuid":       ExecEnvSandboxSetuid,
	"SandboxNamespace":    ExecEnvSandboxNamespace,
	"SandboxAndroid":      ExecEnvSandboxAndroid,
	"ExtraCover":          ExecEnvExtraCover,
	"EnableTun":           ExecEnvEnableTun,
	"EnableNetDev":        ExecEnvEnableNetDev,
	"EnableNetReset":      ExecEnvEnableNetReset,
	"EnableCgroups":       ExecEnvEnableCgroups,
	"EnableCloseFds":      ExecEnvEnableCloseFds,
	"EnableDevlinkPCI":    ExecEnvEnableDevlinkPCI,
	"EnableVhciInjection": ExecEnvEnableVhciInjection,
	"EnableWifi":          ExecEnvEnableWifi,
	"DelayKcovMmap":       ExecEnvDelayKcovMmap,
	"EnableNicVF":         ExecEnvEnableNicVF,
	"EnableDdrdMonitor":   ExecEnvEnableDdrdMonitor,
}

func (v ExecEnv) String() string {
	if s, ok := EnumNamesExecEnv[v]; ok {
		return s
	}
	return "ExecEnv(" + strconv.FormatInt(int64(v), 10) + ")"
}
