// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FileInfoRawT struct {
	Name string `json:"name"`
	Exists bool `json:"exists"`
	UkcUseName uint64 `json:"ukc_use_name"`
	UkcUseStack uint64 `json:"ukc_use_stack"`
	UkcFreeName uint64 `json:"ukc_free_name"`
	UkcFreeStack uint64 `json:"ukc_free_stack"`
	UkcUseAccessDelayTime int32 `json:"ukc_use_access_delay_time"`
	UkcIsValid bool `json:"ukc_is_valid"`
	Error string `json:"error"`
	Data []byte `json:"data"`
}

func (t *FileInfoRawT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	nameOffset := builder.CreateString(t.Name)
	errorOffset := builder.CreateString(t.Error)
	dataOffset := flatbuffers.UOffsetT(0)
	if t.Data != nil {
		dataOffset = builder.CreateByteString(t.Data)
	}
	FileInfoRawStart(builder)
	FileInfoRawAddName(builder, nameOffset)
	FileInfoRawAddExists(builder, t.Exists)
	FileInfoRawAddUkcUseName(builder, t.UkcUseName)
	FileInfoRawAddUkcUseStack(builder, t.UkcUseStack)
	FileInfoRawAddUkcFreeName(builder, t.UkcFreeName)
	FileInfoRawAddUkcFreeStack(builder, t.UkcFreeStack)
	FileInfoRawAddUkcUseAccessDelayTime(builder, t.UkcUseAccessDelayTime)
	FileInfoRawAddUkcIsValid(builder, t.UkcIsValid)
	FileInfoRawAddError(builder, errorOffset)
	FileInfoRawAddData(builder, dataOffset)
	return FileInfoRawEnd(builder)
}

func (rcv *FileInfoRaw) UnPackTo(t *FileInfoRawT) {
	t.Name = string(rcv.Name())
	t.Exists = rcv.Exists()
	t.UkcUseName = rcv.UkcUseName()
	t.UkcUseStack = rcv.UkcUseStack()
	t.UkcFreeName = rcv.UkcFreeName()
	t.UkcFreeStack = rcv.UkcFreeStack()
	t.UkcUseAccessDelayTime = rcv.UkcUseAccessDelayTime()
	t.UkcIsValid = rcv.UkcIsValid()
	t.Error = string(rcv.Error())
	t.Data = rcv.DataBytes()
}

func (rcv *FileInfoRaw) UnPack() *FileInfoRawT {
	if rcv == nil { return nil }
	t := &FileInfoRawT{}
	rcv.UnPackTo(t)
	return t
}

type FileInfoRaw struct {
	_tab flatbuffers.Table
}

func GetRootAsFileInfoRaw(buf []byte, offset flatbuffers.UOffsetT) *FileInfoRaw {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FileInfoRaw{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsFileInfoRaw(buf []byte, offset flatbuffers.UOffsetT) *FileInfoRaw {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FileInfoRaw{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *FileInfoRaw) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FileInfoRaw) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FileInfoRaw) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FileInfoRaw) Exists() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FileInfoRaw) MutateExists(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *FileInfoRaw) UkcUseName() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileInfoRaw) MutateUkcUseName(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *FileInfoRaw) UkcUseStack() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileInfoRaw) MutateUkcUseStack(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *FileInfoRaw) UkcFreeName() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileInfoRaw) MutateUkcFreeName(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *FileInfoRaw) UkcFreeStack() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileInfoRaw) MutateUkcFreeStack(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func (rcv *FileInfoRaw) UkcUseAccessDelayTime() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FileInfoRaw) MutateUkcUseAccessDelayTime(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

func (rcv *FileInfoRaw) UkcIsValid() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FileInfoRaw) MutateUkcIsValid(n bool) bool {
	return rcv._tab.MutateBoolSlot(18, n)
}

func (rcv *FileInfoRaw) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FileInfoRaw) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *FileInfoRaw) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FileInfoRaw) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FileInfoRaw) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func FileInfoRawStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func FileInfoRawAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func FileInfoRawAddExists(builder *flatbuffers.Builder, exists bool) {
	builder.PrependBoolSlot(1, exists, false)
}
func FileInfoRawAddUkcUseName(builder *flatbuffers.Builder, ukcUseName uint64) {
	builder.PrependUint64Slot(2, ukcUseName, 0)
}
func FileInfoRawAddUkcUseStack(builder *flatbuffers.Builder, ukcUseStack uint64) {
	builder.PrependUint64Slot(3, ukcUseStack, 0)
}
func FileInfoRawAddUkcFreeName(builder *flatbuffers.Builder, ukcFreeName uint64) {
	builder.PrependUint64Slot(4, ukcFreeName, 0)
}
func FileInfoRawAddUkcFreeStack(builder *flatbuffers.Builder, ukcFreeStack uint64) {
	builder.PrependUint64Slot(5, ukcFreeStack, 0)
}
func FileInfoRawAddUkcUseAccessDelayTime(builder *flatbuffers.Builder, ukcUseAccessDelayTime int32) {
	builder.PrependInt32Slot(6, ukcUseAccessDelayTime, 0)
}
func FileInfoRawAddUkcIsValid(builder *flatbuffers.Builder, ukcIsValid bool) {
	builder.PrependBoolSlot(7, ukcIsValid, false)
}
func FileInfoRawAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(error), 0)
}
func FileInfoRawAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(data), 0)
}
func FileInfoRawStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func FileInfoRawEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
