// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	"strconv"

	flatbuffers "github.com/google/flatbuffers/go"
)

type HostMessagesRaw byte

const (
	HostMessagesRawNONE          HostMessagesRaw = 0
	HostMessagesRawExecRequest   HostMessagesRaw = 1
	HostMessagesRawSignalUpdate  HostMessagesRaw = 2
	HostMessagesRawCorpusTriaged HostMessagesRaw = 3
	HostMessagesRawStateRequest  HostMessagesRaw = 4
)

var EnumNamesHostMessagesRaw = map[HostMessagesRaw]string{
	HostMessagesRawNONE:          "NONE",
	HostMessagesRawExecRequest:   "ExecRequest",
	HostMessagesRawSignalUpdate:  "SignalUpdate",
	HostMessagesRawCorpusTriaged: "CorpusTriaged",
	HostMessagesRawStateRequest:  "StateRequest",
}

var EnumValuesHostMessagesRaw = map[string]HostMessagesRaw{
	"NONE":          HostMessagesRawNONE,
	"ExecRequest":   HostMessagesRawExecRequest,
	"SignalUpdate":  HostMessagesRawSignalUpdate,
	"CorpusTriaged": HostMessagesRawCorpusTriaged,
	"StateRequest":  HostMessagesRawStateRequest,
}

func (v HostMessagesRaw) String() string {
	if s, ok := EnumNamesHostMessagesRaw[v]; ok {
		return s
	}
	return "HostMessagesRaw(" + strconv.FormatInt(int64(v), 10) + ")"
}

type HostMessagesRawT struct {
	Type HostMessagesRaw
	Value interface{}
}

func (t *HostMessagesRawT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	switch t.Type {
	case HostMessagesRawExecRequest:
		return t.Value.(*ExecRequestRawT).Pack(builder)
	case HostMessagesRawSignalUpdate:
		return t.Value.(*SignalUpdateRawT).Pack(builder)
	case HostMessagesRawCorpusTriaged:
		return t.Value.(*CorpusTriagedRawT).Pack(builder)
	case HostMessagesRawStateRequest:
		return t.Value.(*StateRequestRawT).Pack(builder)
	}
	return 0
}

func (rcv HostMessagesRaw) UnPack(table flatbuffers.Table) *HostMessagesRawT {
	switch rcv {
	case HostMessagesRawExecRequest:
		x := ExecRequestRaw{_tab: table}
		return &HostMessagesRawT{ Type: HostMessagesRawExecRequest, Value: x.UnPack() }
	case HostMessagesRawSignalUpdate:
		x := SignalUpdateRaw{_tab: table}
		return &HostMessagesRawT{ Type: HostMessagesRawSignalUpdate, Value: x.UnPack() }
	case HostMessagesRawCorpusTriaged:
		x := CorpusTriagedRaw{_tab: table}
		return &HostMessagesRawT{ Type: HostMessagesRawCorpusTriaged, Value: x.UnPack() }
	case HostMessagesRawStateRequest:
		x := StateRequestRaw{_tab: table}
		return &HostMessagesRawT{ Type: HostMessagesRawStateRequest, Value: x.UnPack() }
	}
	return nil
}
