// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InfoRequestRawT struct {
	Error    string             `json:"error"`
	Features []*FeatureInfoRawT `json:"features"`
	Files    []*FileInfoRawT    `json:"files"`
}

func (t *InfoRequestRawT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	errorOffset := builder.CreateString(t.Error)
	featuresOffset := flatbuffers.UOffsetT(0)
	if t.Features != nil {
		featuresLength := len(t.Features)
		featuresOffsets := make([]flatbuffers.UOffsetT, featuresLength)
		for j := 0; j < featuresLength; j++ {
			featuresOffsets[j] = t.Features[j].Pack(builder)
		}
		InfoRequestRawStartFeaturesVector(builder, featuresLength)
		for j := featuresLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(featuresOffsets[j])
		}
		featuresOffset = builder.EndVector(featuresLength)
	}
	filesOffset := flatbuffers.UOffsetT(0)
	if t.Files != nil {
		filesLength := len(t.Files)
		filesOffsets := make([]flatbuffers.UOffsetT, filesLength)
		for j := 0; j < filesLength; j++ {
			filesOffsets[j] = t.Files[j].Pack(builder)
		}
		InfoRequestRawStartFilesVector(builder, filesLength)
		for j := filesLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(filesOffsets[j])
		}
		filesOffset = builder.EndVector(filesLength)
	}
	InfoRequestRawStart(builder)
	InfoRequestRawAddError(builder, errorOffset)
	InfoRequestRawAddFeatures(builder, featuresOffset)
	InfoRequestRawAddFiles(builder, filesOffset)
	return InfoRequestRawEnd(builder)
}

func (rcv *InfoRequestRaw) UnPackTo(t *InfoRequestRawT) {
	t.Error = string(rcv.Error())
	featuresLength := rcv.FeaturesLength()
	t.Features = make([]*FeatureInfoRawT, featuresLength)
	for j := 0; j < featuresLength; j++ {
		x := FeatureInfoRaw{}
		rcv.Features(&x, j)
		t.Features[j] = x.UnPack()
	}
	filesLength := rcv.FilesLength()
	t.Files = make([]*FileInfoRawT, filesLength)
	for j := 0; j < filesLength; j++ {
		x := FileInfoRaw{}
		rcv.Files(&x, j)
		t.Files[j] = x.UnPack()
	}
}

func (rcv *InfoRequestRaw) UnPack() *InfoRequestRawT {
	if rcv == nil {
		return nil
	}
	t := &InfoRequestRawT{}
	rcv.UnPackTo(t)
	return t
}

type InfoRequestRaw struct {
	_tab flatbuffers.Table
}

func GetRootAsInfoRequestRaw(buf []byte, offset flatbuffers.UOffsetT) *InfoRequestRaw {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InfoRequestRaw{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsInfoRequestRaw(buf []byte, offset flatbuffers.UOffsetT) *InfoRequestRaw {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InfoRequestRaw{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *InfoRequestRaw) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InfoRequestRaw) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InfoRequestRaw) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InfoRequestRaw) Features(obj *FeatureInfoRaw, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *InfoRequestRaw) FeaturesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *InfoRequestRaw) Files(obj *FileInfoRaw, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *InfoRequestRaw) FilesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func InfoRequestRawStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func InfoRequestRawAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(error), 0)
}
func InfoRequestRawAddFeatures(builder *flatbuffers.Builder, features flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(features), 0)
}
func InfoRequestRawStartFeaturesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func InfoRequestRawAddFiles(builder *flatbuffers.Builder, files flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(files), 0)
}
func InfoRequestRawStartFilesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func InfoRequestRawEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
