// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ProgInfoRawT struct {
	Calls []*CallInfoRawT `json:"calls"`
	ExtraRaw []*CallInfoRawT `json:"extra_raw"`
	Extra *CallInfoRawT `json:"extra"`
	Elapsed uint64 `json:"elapsed"`
	Freshness uint64 `json:"freshness"`
	Ddrd *DdrdRawT `json:"ddrd"`
}

func (t *ProgInfoRawT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	callsOffset := flatbuffers.UOffsetT(0)
	if t.Calls != nil {
		callsLength := len(t.Calls)
		callsOffsets := make([]flatbuffers.UOffsetT, callsLength)
		for j := 0; j < callsLength; j++ {
			callsOffsets[j] = t.Calls[j].Pack(builder)
		}
		ProgInfoRawStartCallsVector(builder, callsLength)
		for j := callsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(callsOffsets[j])
		}
		callsOffset = builder.EndVector(callsLength)
	}
	extraRawOffset := flatbuffers.UOffsetT(0)
	if t.ExtraRaw != nil {
		extraRawLength := len(t.ExtraRaw)
		extraRawOffsets := make([]flatbuffers.UOffsetT, extraRawLength)
		for j := 0; j < extraRawLength; j++ {
			extraRawOffsets[j] = t.ExtraRaw[j].Pack(builder)
		}
		ProgInfoRawStartExtraRawVector(builder, extraRawLength)
		for j := extraRawLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(extraRawOffsets[j])
		}
		extraRawOffset = builder.EndVector(extraRawLength)
	}
	extraOffset := t.Extra.Pack(builder)
	ddrdOffset := t.Ddrd.Pack(builder)
	ProgInfoRawStart(builder)
	ProgInfoRawAddCalls(builder, callsOffset)
	ProgInfoRawAddExtraRaw(builder, extraRawOffset)
	ProgInfoRawAddExtra(builder, extraOffset)
	ProgInfoRawAddElapsed(builder, t.Elapsed)
	ProgInfoRawAddFreshness(builder, t.Freshness)
	ProgInfoRawAddDdrd(builder, ddrdOffset)
	return ProgInfoRawEnd(builder)
}

func (rcv *ProgInfoRaw) UnPackTo(t *ProgInfoRawT) {
	callsLength := rcv.CallsLength()
	t.Calls = make([]*CallInfoRawT, callsLength)
	for j := 0; j < callsLength; j++ {
		x := CallInfoRaw{}
		rcv.Calls(&x, j)
		t.Calls[j] = x.UnPack()
	}
	extraRawLength := rcv.ExtraRawLength()
	t.ExtraRaw = make([]*CallInfoRawT, extraRawLength)
	for j := 0; j < extraRawLength; j++ {
		x := CallInfoRaw{}
		rcv.ExtraRaw(&x, j)
		t.ExtraRaw[j] = x.UnPack()
	}
	t.Extra = rcv.Extra(nil).UnPack()
	t.Elapsed = rcv.Elapsed()
	t.Freshness = rcv.Freshness()
	t.Ddrd = rcv.Ddrd(nil).UnPack()
}

func (rcv *ProgInfoRaw) UnPack() *ProgInfoRawT {
	if rcv == nil { return nil }
	t := &ProgInfoRawT{}
	rcv.UnPackTo(t)
	return t
}

type ProgInfoRaw struct {
	_tab flatbuffers.Table
}

func GetRootAsProgInfoRaw(buf []byte, offset flatbuffers.UOffsetT) *ProgInfoRaw {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ProgInfoRaw{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsProgInfoRaw(buf []byte, offset flatbuffers.UOffsetT) *ProgInfoRaw {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ProgInfoRaw{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ProgInfoRaw) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ProgInfoRaw) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ProgInfoRaw) Calls(obj *CallInfoRaw, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ProgInfoRaw) CallsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ProgInfoRaw) ExtraRaw(obj *CallInfoRaw, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ProgInfoRaw) ExtraRawLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ProgInfoRaw) Extra(obj *CallInfoRaw) *CallInfoRaw {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(CallInfoRaw)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ProgInfoRaw) Elapsed() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ProgInfoRaw) MutateElapsed(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *ProgInfoRaw) Freshness() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ProgInfoRaw) MutateFreshness(n uint64) bool {
	return rcv._tab.MutateUint64Slot(12, n)
}

func (rcv *ProgInfoRaw) Ddrd(obj *DdrdRaw) *DdrdRaw {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DdrdRaw)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ProgInfoRawStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func ProgInfoRawAddCalls(builder *flatbuffers.Builder, calls flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(calls), 0)
}
func ProgInfoRawStartCallsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ProgInfoRawAddExtraRaw(builder *flatbuffers.Builder, extraRaw flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(extraRaw), 0)
}
func ProgInfoRawStartExtraRawVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ProgInfoRawAddExtra(builder *flatbuffers.Builder, extra flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(extra), 0)
}
func ProgInfoRawAddElapsed(builder *flatbuffers.Builder, elapsed uint64) {
	builder.PrependUint64Slot(3, elapsed, 0)
}
func ProgInfoRawAddFreshness(builder *flatbuffers.Builder, freshness uint64) {
	builder.PrependUint64Slot(4, freshness, 0)
}
func ProgInfoRawAddDdrd(builder *flatbuffers.Builder, ddrd flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(ddrd), 0)
}
func ProgInfoRawEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
