// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import "strconv"

type RequestFlag uint64

const (
	RequestFlagReturnOutput RequestFlag = 1
	RequestFlagReturnError  RequestFlag = 2
)

var EnumNamesRequestFlag = map[RequestFlag]string{
	RequestFlagReturnOutput: "ReturnOutput",
	RequestFlagReturnError:  "ReturnError",
}

var EnumValuesRequestFlag = map[string]RequestFlag{
	"ReturnOutput": RequestFlagReturnOutput,
	"ReturnError":  RequestFlagReturnError,
}

func (v RequestFlag) String() string {
	if s, ok := EnumNamesRequestFlag[v]; ok {
		return s
	}
	return "RequestFlag(" + strconv.FormatInt(int64(v), 10) + ")"
}
