// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import "strconv"

type RequestType uint64

const (
	RequestTypeProgram RequestType = 0
	RequestTypeBinary  RequestType = 1
	RequestTypeGlob    RequestType = 2
)

var EnumNamesRequestType = map[RequestType]string{
	RequestTypeProgram: "Program",
	RequestTypeBinary:  "Binary",
	RequestTypeGlob:    "Glob",
}

var EnumValuesRequestType = map[string]RequestType{
	"Program": RequestTypeProgram,
	"Binary":  RequestTypeBinary,
	"Glob":    RequestTypeGlob,
}

func (v RequestType) String() string {
	if s, ok := EnumNamesRequestType[v]; ok {
		return s
	}
	return "RequestType(" + strconv.FormatInt(int64(v), 10) + ")"
}
