// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SnapshotHeaderT struct {
	State        SnapshotState `json:"state"`
	OutputOffset uint32        `json:"output_offset"`
	OutputSize   uint32        `json:"output_size"`
}

func (t *SnapshotHeaderT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	SnapshotHeaderStart(builder)
	SnapshotHeaderAddState(builder, t.State)
	SnapshotHeaderAddOutputOffset(builder, t.OutputOffset)
	SnapshotHeaderAddOutputSize(builder, t.OutputSize)
	return SnapshotHeaderEnd(builder)
}

func (rcv *SnapshotHeader) UnPackTo(t *SnapshotHeaderT) {
	t.State = rcv.State()
	t.OutputOffset = rcv.OutputOffset()
	t.OutputSize = rcv.OutputSize()
}

func (rcv *SnapshotHeader) UnPack() *SnapshotHeaderT {
	if rcv == nil {
		return nil
	}
	t := &SnapshotHeaderT{}
	rcv.UnPackTo(t)
	return t
}

type SnapshotHeader struct {
	_tab flatbuffers.Table
}

func GetRootAsSnapshotHeader(buf []byte, offset flatbuffers.UOffsetT) *SnapshotHeader {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SnapshotHeader{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSnapshotHeader(buf []byte, offset flatbuffers.UOffsetT) *SnapshotHeader {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SnapshotHeader{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SnapshotHeader) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SnapshotHeader) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SnapshotHeader) State() SnapshotState {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return SnapshotState(rcv._tab.GetUint64(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *SnapshotHeader) MutateState(n SnapshotState) bool {
	return rcv._tab.MutateUint64Slot(4, uint64(n))
}

func (rcv *SnapshotHeader) OutputOffset() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SnapshotHeader) MutateOutputOffset(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *SnapshotHeader) OutputSize() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SnapshotHeader) MutateOutputSize(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func SnapshotHeaderStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func SnapshotHeaderAddState(builder *flatbuffers.Builder, state SnapshotState) {
	builder.PrependUint64Slot(0, uint64(state), 0)
}
func SnapshotHeaderAddOutputOffset(builder *flatbuffers.Builder, outputOffset uint32) {
	builder.PrependUint32Slot(1, outputOffset, 0)
}
func SnapshotHeaderAddOutputSize(builder *flatbuffers.Builder, outputSize uint32) {
	builder.PrependUint32Slot(2, outputSize, 0)
}
func SnapshotHeaderEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
