// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SnapshotHandshakeT struct {
	CoverEdges       bool    `json:"cover_edges"`
	Kernel64Bit      bool    `json:"kernel_64_bit"`
	Slowdown         int32   `json:"slowdown"`
	SyscallTimeoutMs int32   `json:"syscall_timeout_ms"`
	ProgramTimeoutMs int32   `json:"program_timeout_ms"`
	Features         Feature `json:"features"`
	EnvFlags         ExecEnv `json:"env_flags"`
	SandboxArg       int64   `json:"sandbox_arg"`
}

func (t *SnapshotHandshakeT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	SnapshotHandshakeStart(builder)
	SnapshotHandshakeAddCoverEdges(builder, t.CoverEdges)
	SnapshotHandshakeAddKernel64Bit(builder, t.Kernel64Bit)
	SnapshotHandshakeAddSlowdown(builder, t.Slowdown)
	SnapshotHandshakeAddSyscallTimeoutMs(builder, t.SyscallTimeoutMs)
	SnapshotHandshakeAddProgramTimeoutMs(builder, t.ProgramTimeoutMs)
	SnapshotHandshakeAddFeatures(builder, t.Features)
	SnapshotHandshakeAddEnvFlags(builder, t.EnvFlags)
	SnapshotHandshakeAddSandboxArg(builder, t.SandboxArg)
	return SnapshotHandshakeEnd(builder)
}

func (rcv *SnapshotHandshake) UnPackTo(t *SnapshotHandshakeT) {
	t.CoverEdges = rcv.CoverEdges()
	t.Kernel64Bit = rcv.Kernel64Bit()
	t.Slowdown = rcv.Slowdown()
	t.SyscallTimeoutMs = rcv.SyscallTimeoutMs()
	t.ProgramTimeoutMs = rcv.ProgramTimeoutMs()
	t.Features = rcv.Features()
	t.EnvFlags = rcv.EnvFlags()
	t.SandboxArg = rcv.SandboxArg()
}

func (rcv *SnapshotHandshake) UnPack() *SnapshotHandshakeT {
	if rcv == nil {
		return nil
	}
	t := &SnapshotHandshakeT{}
	rcv.UnPackTo(t)
	return t
}

type SnapshotHandshake struct {
	_tab flatbuffers.Table
}

func GetRootAsSnapshotHandshake(buf []byte, offset flatbuffers.UOffsetT) *SnapshotHandshake {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SnapshotHandshake{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSnapshotHandshake(buf []byte, offset flatbuffers.UOffsetT) *SnapshotHandshake {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SnapshotHandshake{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SnapshotHandshake) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SnapshotHandshake) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SnapshotHandshake) CoverEdges() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SnapshotHandshake) MutateCoverEdges(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *SnapshotHandshake) Kernel64Bit() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SnapshotHandshake) MutateKernel64Bit(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *SnapshotHandshake) Slowdown() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SnapshotHandshake) MutateSlowdown(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *SnapshotHandshake) SyscallTimeoutMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SnapshotHandshake) MutateSyscallTimeoutMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *SnapshotHandshake) ProgramTimeoutMs() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SnapshotHandshake) MutateProgramTimeoutMs(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func (rcv *SnapshotHandshake) Features() Feature {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return Feature(rcv._tab.GetUint64(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *SnapshotHandshake) MutateFeatures(n Feature) bool {
	return rcv._tab.MutateUint64Slot(14, uint64(n))
}

func (rcv *SnapshotHandshake) EnvFlags() ExecEnv {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return ExecEnv(rcv._tab.GetUint64(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *SnapshotHandshake) MutateEnvFlags(n ExecEnv) bool {
	return rcv._tab.MutateUint64Slot(16, uint64(n))
}

func (rcv *SnapshotHandshake) SandboxArg() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SnapshotHandshake) MutateSandboxArg(n int64) bool {
	return rcv._tab.MutateInt64Slot(18, n)
}

func SnapshotHandshakeStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func SnapshotHandshakeAddCoverEdges(builder *flatbuffers.Builder, coverEdges bool) {
	builder.PrependBoolSlot(0, coverEdges, false)
}
func SnapshotHandshakeAddKernel64Bit(builder *flatbuffers.Builder, kernel64Bit bool) {
	builder.PrependBoolSlot(1, kernel64Bit, false)
}
func SnapshotHandshakeAddSlowdown(builder *flatbuffers.Builder, slowdown int32) {
	builder.PrependInt32Slot(2, slowdown, 0)
}
func SnapshotHandshakeAddSyscallTimeoutMs(builder *flatbuffers.Builder, syscallTimeoutMs int32) {
	builder.PrependInt32Slot(3, syscallTimeoutMs, 0)
}
func SnapshotHandshakeAddProgramTimeoutMs(builder *flatbuffers.Builder, programTimeoutMs int32) {
	builder.PrependInt32Slot(4, programTimeoutMs, 0)
}
func SnapshotHandshakeAddFeatures(builder *flatbuffers.Builder, features Feature) {
	builder.PrependUint64Slot(5, uint64(features), 0)
}
func SnapshotHandshakeAddEnvFlags(builder *flatbuffers.Builder, envFlags ExecEnv) {
	builder.PrependUint64Slot(6, uint64(envFlags), 0)
}
func SnapshotHandshakeAddSandboxArg(builder *flatbuffers.Builder, sandboxArg int64) {
	builder.PrependInt64Slot(7, sandboxArg, 0)
}
func SnapshotHandshakeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
