// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SnapshotRequestT struct {
	ExecFlags ExecFlag `json:"exec_flags"`
	NumCalls int32 `json:"num_calls"`
	AllCallSignal uint64 `json:"all_call_signal"`
	AllExtraSignal bool `json:"all_extra_signal"`
	ProgData []byte `json:"prog_data"`
}

func (t *SnapshotRequestT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	progDataOffset := flatbuffers.UOffsetT(0)
	if t.ProgData != nil {
		progDataOffset = builder.CreateByteString(t.ProgData)
	}
	SnapshotRequestStart(builder)
	SnapshotRequestAddExecFlags(builder, t.ExecFlags)
	SnapshotRequestAddNumCalls(builder, t.NumCalls)
	SnapshotRequestAddAllCallSignal(builder, t.AllCallSignal)
	SnapshotRequestAddAllExtraSignal(builder, t.AllExtraSignal)
	SnapshotRequestAddProgData(builder, progDataOffset)
	return SnapshotRequestEnd(builder)
}

func (rcv *SnapshotRequest) UnPackTo(t *SnapshotRequestT) {
	t.ExecFlags = rcv.ExecFlags()
	t.NumCalls = rcv.NumCalls()
	t.AllCallSignal = rcv.AllCallSignal()
	t.AllExtraSignal = rcv.AllExtraSignal()
	t.ProgData = rcv.ProgDataBytes()
}

func (rcv *SnapshotRequest) UnPack() *SnapshotRequestT {
	if rcv == nil { return nil }
	t := &SnapshotRequestT{}
	rcv.UnPackTo(t)
	return t
}

type SnapshotRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSnapshotRequest(buf []byte, offset flatbuffers.UOffsetT) *SnapshotRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SnapshotRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSnapshotRequest(buf []byte, offset flatbuffers.UOffsetT) *SnapshotRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SnapshotRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SnapshotRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SnapshotRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SnapshotRequest) ExecFlags() ExecFlag {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ExecFlag(rcv._tab.GetUint64(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *SnapshotRequest) MutateExecFlags(n ExecFlag) bool {
	return rcv._tab.MutateUint64Slot(4, uint64(n))
}

func (rcv *SnapshotRequest) NumCalls() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SnapshotRequest) MutateNumCalls(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *SnapshotRequest) AllCallSignal() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SnapshotRequest) MutateAllCallSignal(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *SnapshotRequest) AllExtraSignal() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SnapshotRequest) MutateAllExtraSignal(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *SnapshotRequest) ProgData(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *SnapshotRequest) ProgDataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SnapshotRequest) ProgDataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SnapshotRequest) MutateProgData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func SnapshotRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func SnapshotRequestAddExecFlags(builder *flatbuffers.Builder, execFlags ExecFlag) {
	builder.PrependUint64Slot(0, uint64(execFlags), 0)
}
func SnapshotRequestAddNumCalls(builder *flatbuffers.Builder, numCalls int32) {
	builder.PrependInt32Slot(1, numCalls, 0)
}
func SnapshotRequestAddAllCallSignal(builder *flatbuffers.Builder, allCallSignal uint64) {
	builder.PrependUint64Slot(2, allCallSignal, 0)
}
func SnapshotRequestAddAllExtraSignal(builder *flatbuffers.Builder, allExtraSignal bool) {
	builder.PrependBoolSlot(3, allExtraSignal, false)
}
func SnapshotRequestAddProgData(builder *flatbuffers.Builder, progData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(progData), 0)
}
func SnapshotRequestStartProgDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func SnapshotRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
