// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatrpc

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StateRequestRawT struct {
}

func (t *StateRequestRawT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil { return 0 }
	StateRequestRawStart(builder)
	return StateRequestRawEnd(builder)
}

func (rcv *StateRequestRaw) UnPackTo(t *StateRequestRawT) {
}

func (rcv *StateRequestRaw) UnPack() *StateRequestRawT {
	if rcv == nil { return nil }
	t := &StateRequestRawT{}
	rcv.UnPackTo(t)
	return t
}

type StateRequestRaw struct {
	_tab flatbuffers.Table
}

func GetRootAsStateRequestRaw(buf []byte, offset flatbuffers.UOffsetT) *StateRequestRaw {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StateRequestRaw{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsStateRequestRaw(buf []byte, offset flatbuffers.UOffsetT) *StateRequestRaw {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StateRequestRaw{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *StateRequestRaw) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StateRequestRaw) Table() flatbuffers.Table {
	return rcv._tab
}

func StateRequestRawStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func StateRequestRawEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
