// KCSAN Barrier-style Reproducer Template
// Auto-generated by syz-kcsan-repro
// This template forks two processes that synchronize via futex barrier,
// then execute syscall sequences derived from syzkaller programs.
// The goal is to trigger concurrent memory accesses detectable by KCSAN.

#define _GNU_SOURCE
#include <errno.h>
#include <fcntl.h>
#include <linux/futex.h>
#include <pthread.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

// ============================================================
// Barrier implementation using shared memory futex
// ============================================================
static volatile uint32_t* barrier_futex;

static void barrier_init(void)
{
    barrier_futex = (volatile uint32_t*)mmap(
        NULL, sizeof(uint32_t),
        PROT_READ | PROT_WRITE,
        MAP_SHARED | MAP_ANONYMOUS, -1, 0);
    if (barrier_futex == MAP_FAILED) {
        perror("mmap barrier");
        exit(1);
    }
    *barrier_futex = 0;
}

// Two-process barrier: each process increments the futex value,
// then waits until it reaches 2 (both arrived).
static void barrier_wait(void)
{
    uint32_t val = __sync_add_and_fetch((uint32_t*)barrier_futex, 1);
    if (val < 2) {
        // Wait until the other process arrives
        while (__sync_val_compare_and_swap((uint32_t*)barrier_futex, 2, 2) < 2) {
            syscall(SYS_futex, barrier_futex, FUTEX_WAIT, val, NULL, NULL, 0);
        }
    } else {
        // Wake the other process
        syscall(SYS_futex, barrier_futex, FUTEX_WAKE, 1, NULL, NULL, 0);
    }
}

// Reset barrier for reuse in next iteration
static void barrier_reset(void)
{
    *barrier_futex = 0;
    __sync_synchronize();
}

// ============================================================
// KCSAN runtime tuning via sysfs (optional, best-effort)
// ============================================================
static void kcsan_tune(void)
{
    // Set skip_watch=5 for targeted mode (aggressive but manageable overhead)
    int fd = open("/sys/module/kcsan/parameters/skip_watch", O_WRONLY);
    if (fd >= 0) {
        write(fd, "5", 1);
        close(fd);
    }
    // Set udelay_task for timing window
    fd = open("/sys/module/kcsan/parameters/udelay_task", O_WRONLY);
    if (fd >= 0) {
        write(fd, "200", 3);
        close(fd);
    }
}

// ============================================================
// Placeholder: syscall sequences from program 0 and program 1
// These will be replaced by gen_reproducer.py with actual
// C code generated by syz-prog2c
// ============================================================

// @PROC0_INCLUDES@

// @PROC1_INCLUDES@

static void execute_prog0(int delay_us)
{
    // @PROC0_BODY@
    (void)delay_us;
}

static void execute_prog1(int delay_us)
{
    // @PROC1_BODY@
    (void)delay_us;
}

// ============================================================
// Main: fork + barrier + execute
// ============================================================
int main(int argc, char** argv)
{
    int repeat = 100;
    int delay_us = 0;

    if (argc > 1)
        repeat = atoi(argv[1]);
    if (argc > 2)
        delay_us = atoi(argv[2]);

    printf("[kcsan-repro] repeat=%d, delay_us=%d\n", repeat, delay_us);

    kcsan_tune();
    barrier_init();

    for (int iter = 0; iter < repeat; iter++) {
        barrier_reset();

        pid_t pid = fork();
        if (pid < 0) {
            perror("fork");
            exit(1);
        }

        if (pid == 0) {
            // Child: execute program 1
            barrier_wait();
            if (delay_us > 0)
                usleep(delay_us);
            execute_prog1(delay_us);
            _exit(0);
        } else {
            // Parent: execute program 0
            barrier_wait();
            execute_prog0(delay_us);
            int status;
            waitpid(pid, &status, 0);
        }
    }

    printf("[kcsan-repro] Done. Check dmesg for KCSAN reports.\n");
    return 0;
}
